[package]
name = "ppf"
version = "0.1.0"
authors = ["John Peel <john@dgby.org>"]
edition = "2018"
repository = "https://github.com/JohnPeel/ppf"
license = "MIT"

[dependencies]
log = "0.4.14"
env_logger = "0.9.0"
nom = "6.2.1"
num-traits = "0.2.14"
num-derive = "0.3.3"
